// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2dtqt74TOkST7lwAtCBp4PNuJ5keA7U',
    appId: '1:214262866140:web:dd35e62f3dfe6cde0f9419',
    messagingSenderId: '214262866140',
    projectId: 'flutter-x-143',
    authDomain: 'flutter-x-143.firebaseapp.com',
    storageBucket: 'flutter-x-143.firebasestorage.app',
    measurementId: 'G-8B52G17KC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThff50A0KcY7qxgh2DxrWgRgcQKHkgjg',
    appId: '1:214262866140:android:ed2ff83fd2c030970f9419',
    messagingSenderId: '214262866140',
    projectId: 'flutter-x-143',
    storageBucket: 'flutter-x-143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwsc3JA0RiNRvt33oOtOjxApjpCEy3CY',
    appId: '1:214262866140:ios:dce8d2c27749066f0f9419',
    messagingSenderId: '214262866140',
    projectId: 'flutter-x-143',
    storageBucket: 'flutter-x-143.firebasestorage.app',
    iosBundleId: 'com.example.timetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZwsc3JA0RiNRvt33oOtOjxApjpCEy3CY',
    appId: '1:214262866140:ios:dce8d2c27749066f0f9419',
    messagingSenderId: '214262866140',
    projectId: 'flutter-x-143',
    storageBucket: 'flutter-x-143.firebasestorage.app',
    iosBundleId: 'com.example.timetable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2dtqt74TOkST7lwAtCBp4PNuJ5keA7U',
    appId: '1:214262866140:web:cdda604d8bfed4270f9419',
    messagingSenderId: '214262866140',
    projectId: 'flutter-x-143',
    authDomain: 'flutter-x-143.firebaseapp.com',
    storageBucket: 'flutter-x-143.firebasestorage.app',
    measurementId: 'G-1PTR603K4D',
  );
}
